#!/usr/bin/env python3
"""Materialise the Codex-authored label-comparison package for external plan #11."""
from pathlib import Path
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from schemas_v8 import (ResearchSource, ResearchClaim, ResearchPack, Beat, Overlay, Script,
                        ComplianceVerdict, FactReview, FactCheckItem, Frame, FramePlan,
                        QACheck, QAReport, PublishPackage)

RUN = ROOT / "runs/vitallogic_bad_pl/2026-08-22_v8-skyr-grecki-naturalny-etykieta"
HERO = "original adult Polish office analyst, age 34, short chestnut hair, small round black glasses, mint shirt under a mustard cardigan, navy trousers, slim build, expressive friendly face, no logos, no animal ears, no branded costume"
STYLE = "Vertical 9:16 bright pastel 2D hand-drawn editorial cartoon, thick black ink contours, flat cel shading, cyan lemon mint pink lilac and warm cream palette, clean safe space for deterministic Polish captions; no fake text, no watermark"

def dump(name, value):
    RUN.mkdir(parents=True, exist_ok=True)
    (RUN / name).write_text(value.model_dump_json(indent=2) + "\n" if hasattr(value, "model_dump_json") else json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

sources = [
 ResearchSource(id="SRC-01", title="Skyr naturalny 150 g", publisher="Piątnica", url="https://piatnica.com.pl/produkt/skyr-naturalny-150g/", source_type="other", year=2026, evidence_summary="Karta producenta podaje na 100 g: 64 kcal, 12 g białka, 0 g tłuszczu oraz 4,1 g cukrów; skład to mleko pasteryzowane i żywe kultury bakterii jogurtowych."),
 ResearchSource(id="SRC-02", title="Jogurt Polski naturalny", publisher="Mlekovita", url="https://mlekovita.com.pl/produkt/jogurt-polski-naturalny-768", source_type="other", year=2026, evidence_summary="Karta producenta podaje na 100 g: 64 kcal, 3,4 g białka, 3,5 g tłuszczu, 4,0 g cukrów oraz skład z mleka i żywych kultur bakterii."),
 ResearchSource(id="SRC-03", title="Jogurt naturalny typ grecki 10% bez laktozy", publisher="Mlekovita", url="https://mlekovita.com.pl/produkt/jogurt-naturalny-typ-grecki-bez-laktozy-980", source_type="other", year=2026, evidence_summary="Karta producenta podaje na 100 g: 118 kcal, 3,0 g białka, 10 g tłuszczu i 4,0 g cukrów; produkt ma 400 g i zawartość laktozy poniżej 0,01 g/100 g."),
 ResearchSource(id="SRC-04", title="Produkty proteinowe – czy warto wybierać zamienniki ze zwiększoną ilością białka", publisher="Narodowe Centrum Edukacji Żywieniowej", url="https://ncez.pzh.gov.pl/abc-zywienia/zasady-zdrowego-zywienia/produkty-proteinowe-czy-warto-wybierac-zamienniki-ze-zwiekszona-iloscia-bialka/", source_type="official_guideline", year=2024, evidence_summary="NCEŻ pokazuje przykładowe porównanie jogurtów i podkreśla, że przy wyborze nie należy kierować się wyłącznie deklaracją wysokiej zawartości białka; liczą się także tłuszcz, cukry, porcja i skład."),
 ResearchSource(id="SRC-05", title="Żywność w świetle etykiet okiem konsumenta", publisher="Narodowe Centrum Edukacji Żywieniowej", url="https://ncez.pzh.gov.pl/dla-producentow-zywnosci/zywnosc-w-swietle-etykiet-okiem-konsumenta-2/", source_type="official_guideline", year=2026, evidence_summary="NCEŻ wyjaśnia, że tabela podaje energię, tłuszcz, cukry, białko i sól zwykle na 100 g lub 100 ml, a przy większych i mniejszych opakowaniach trzeba uwzględnić porcję."),
]
claims = [
 ResearchClaim(id="CLM-01", neutral_claim="W trzech wybranych etykietach skyr Piątnica ma 12 g białka na 100 g, wobec 3,4 g w Jogurcie Polskim naturalnym i 3,0 g w greckim 10% Mlekovita.", verdict="supported", confidence="high", source_ids=["SRC-01","SRC-02","SRC-03"], allowed_wording="W tych trzech przykładach skyr ma najwięcej białka na 100 gramów.", forbidden_wording=["każdy skyr zawsze wygrywa","skyr jest najzdrowszy"], limitations="To trzy konkretne produkty, nie ranking wszystkich jogurtów na rynku.", risk_level="low"),
 ResearchClaim(id="CLM-02", neutral_claim="W trzech wybranych etykietach naturalny i skyr mają po około 64 kcal na 100 g, a grecki 10% ma 118 kcal i 10 g tłuszczu.", verdict="supported", confidence="high", source_ids=["SRC-01","SRC-02","SRC-03"], allowed_wording="W tym greckim 10% większa kremowość idzie z 10 gramami tłuszczu i 118 kilokaloriami na 100 gramów.", forbidden_wording=["tłuszcz jest zły","grecki jest niezdrowy"], limitations="Wartości odnoszą się do konkretnego wariantu greckiego 10% bez laktozy.", risk_level="low"),
 ResearchClaim(id="CLM-03", neutral_claim="W trzech wybranych naturalnych produktach etykieta podaje 4,0–4,1 g cukrów na 100 g.", verdict="supported", confidence="high", source_ids=["SRC-01","SRC-02","SRC-03"], allowed_wording="W tych trzech naturalnych wariantach cukry są bardzo podobne: około 4 gramów na 100 gramów.", forbidden_wording=["cukier jest identyczny w każdym jogurcie","zero cukru"], limitations="Nie porównuje to jogurtów smakowych ani wszystkich marek.", risk_level="low"),
 ResearchClaim(id="CLM-04", neutral_claim="NCEŻ zaleca, by przy produktach proteinowych nie kierować się wyłącznie napisem o wysokiej zawartości białka; tabela i skład dostarczają szerszego porównania.", verdict="supported", confidence="high", source_ids=["SRC-04","SRC-05"], allowed_wording="Nie wybieraj po jednym haśle z przodu: porównaj białko, tłuszcz, cukry i porcję.", forbidden_wording=["high protein to oszustwo","lista składników zawsze mówi wszystko"], limitations="Priorytety wyboru zależą od dania, porcji i potrzeb konkretnej osoby.", risk_level="medium", display_source=True),
 ResearchClaim(id="CLM-05", neutral_claim="Tabela wartości odżywczej odnosi się zwykle do 100 g lub 100 ml, więc porcja i masa opakowania zmieniają ilość składników spożytą jednorazowo.", verdict="supported", confidence="high", source_ids=["SRC-05"], allowed_wording="Najpierw porównaj 100 gramów, potem sprawdź swoją porcję.", forbidden_wording=["jedna porcja jest dobra dla każdego"], limitations="Film nie ustala indywidualnej porcji ani planu diety.", risk_level="low"),
]
beats = [
 ("Skyr, grecki czy naturalny? Na półce robią rozmowę kwalifikacyjną.","SKYR / GRECKI / NATURALNY","Hook: three generic unbranded yogurt cups face each other like job candidates; hero looks between them with amused suspicion.",2.2,"hook",["CLM-04"],"kwalifikacyjną"),
 ("Pierwszy filtr: najpierw porównaj sto gramów, nie wielkość kubka.","NA 100 g","Hero holds a tiny magnifying glass over three identical-size nutrition panels made of blank lines and colored bars, focused analytical gaze.",2.3,"hook",["CLM-05"],"sto"),
 ("W tych trzech przykładach skyr ma dwanaście gramów białka na sto gramów.","SKYR: 12 g BIAŁKA","Macro skyr cup with a large clean protein bar rising, hero points at it with surprised raised eyebrows.",2.8,"body",["CLM-01"],"dwanaście"),
 ("Naturalny ma trzy przecinek cztery, a grecki dziesięcioprocentowy trzy gramy.","NATURALNY 3,4 g • GRECKI 3 g","Split macro: natural and Greek generic cups with shorter protein bars; hero makes a playful referee gesture, gaze moves across both.",3.0,"body",["CLM-01"],"trzy"),
 ("Plot twist: cukry w tych naturalnych wariantach są prawie remisem — około czterech gramów.","CUKRY: ok. 4 g","Three clean generic cups on a tiny podium, identical sugar-dot rows, hero gives an ironic surprised shrug.",2.8,"body",["CLM-03"],"remisem"),
 ("Za to ten grecki dziesięcioprocentowy ma dziesięć gramów tłuszczu i sto osiemnaście kilokalorii.","GRECKI 10%: 10 g TŁUSZCZU","Extreme macro of a creamy Greek yogurt swirl beside a bold fat droplet shape, hero reacts with knowing comic seriousness.",3.0,"body",["CLM-02"],"dziesięć"),
 ("Czyli białko nie wybiera za ciebie całego śniadania. Produkt protestuje, tabela nie.","NIE TYLKO BIAŁKO","Office-style mock interview: a generic protein badge tries to speak into a microphone while the nutrition table calmly holds up a stop hand; hero smiles.",2.8,"body",["CLM-04"],"tabela"),
 ("Do owoców i szybkiej przekąski? Szukaj więcej białka. Do sosu? Kremowość też ma sens.","DO CZEGO GO UŻYWASZ?","Wide kitchen split: skyr bowl with fruit on one side, Greek yogurt dip on the other; hero points to each with a warm practical expression.",3.0,"body",["CLM-01","CLM-02"],"sens"),
 ("Zasada półki: białko, tłuszcz, cukry, porcja — i dopiero potem koszyk.","4 RZECZY Z ETYKIETY","Final wide: hero places four simple colored check cards beside generic yogurt cups; decisive friendly gaze to viewer.",3.0,"payoff",["CLM-04","CLM-05"],"koszyk"),
]
beat_objs=[Beat(voiceover=a,on_screen_text=b,visual_cue=c,dur_s=d,act=e,claim_ids=f,emphasis=g) for a,b,c,d,e,f,g in beats]
overlays=[
 Overlay(kind="callout",beat_idx=2,value="12 g",claim_ids=["CLM-01"]),
 Overlay(kind="versus",beat_idx=3,label="NATURALNY",value="3,4 g",label_b="GRECKI 10%",value_b="3 g",winner="none",claim_ids=["CLM-01"]),
 Overlay(kind="versus",beat_idx=5,label="TŁUSZCZ",value="10 g",label_b="ENERGIA",value_b="118 kcal",winner="none",claim_ids=["CLM-02"]),
 Overlay(kind="source",beat_idx=6,label="NCEŻ 2024",source_finding="Nie wybieraj tylko po białku",claim_ids=["CLM-04"]),
 Overlay(kind="list",beat_idx=8,label="PORÓWNAJ",items=["białko","tłuszcz","cukry","porcję"],claim_ids=["CLM-04","CLM-05"]),
]
script=Script(lang="pl",rubric="at_shelf",format="versus",hook=beat_objs[0].voiceover,poster_text="TRZY JOGURTY, JEDNA TABELA",beats=beat_objs,overlays=overlays,payload="Porównaj na 100 g białko, tłuszcz i cukry, a potem dopasuj kubek do swojego dania i porcji.",turn_beat_idx=6,payoff_card="BIAŁKO • TŁUSZCZ • CUKRY • PORCJA",cta="",total_dur_s=sum(x.dur_s for x in beat_objs),central_claim_id="CLM-04",poster_claim_ids=["CLM-04"],payload_claim_ids=["CLM-01","CLM-02","CLM-03","CLM-05"],payoff_claim_ids=["CLM-04","CLM-05"])
prompts=[
 f"{STYLE}. extreme_macro. {HERO}. Three generic unbranded yogurt cups: tall skyr, creamy Greek style, simple natural yogurt, face each other like nervous job candidates on a pastel supermarket shelf. COMPOSITION CENTER: three cups and hero's amused suspicious face. EYE PATH: cups to hero's eyes. Hero open hands, raised eyebrow, gaze at cups.",
 f"{STYLE}. macro. {HERO}. Hero uses an oversized magnifying glass to inspect three clean nutrition panels rendered as blank colored rows with no letters or digits. COMPOSITION CENTER: magnifying glass and 100-gram concept represented by identical three weights. EYE PATH: lens to three equal weights. Focused analytical eyes, pinching gesture.",
 f"{STYLE}. macro. {HERO}. Generic white skyr cup and a tall mint protein bar rising beside it, no letters or digits. COMPOSITION CENTER: rising protein bar. EYE PATH: cup to bar to hero's astonished face. Hero points up, eyebrows raised, direct gaze at bar.",
 f"{STYLE}. medium split composition. {HERO}. Generic natural yogurt cup left and creamy Greek style yogurt cup right, each with a shorter equal-height protein bar, no letters or digits. COMPOSITION CENTER: two protein bars. EYE PATH: left cup to right cup then hero. Hero is a playful referee, one hand toward each cup, wry smile.",
 f"{STYLE}. wide. {HERO}. Three generic natural yogurt cups stand on a tiny shared podium, each with the same row of four small sugar cubes, no text or digits. COMPOSITION CENTER: the equal sugar-cube rows. EYE PATH: podium to hero's ironic shrug. Hero eyes wide, palms up, gaze at cubes.",
 f"{STYLE}. extreme_macro. {HERO}. Creamy Greek yogurt swirl with a large clean golden fat droplet and a warm calorie sun icon, no lettering or digits. COMPOSITION CENTER: fat droplet and swirl. EYE PATH: swirl to droplet to hero. Hero holds a tiny clipboard, knowing comic serious face, gaze at droplet.",
 f"{STYLE}. medium whimsical office interview. {HERO}. A generic protein badge tries to speak into a tiny microphone while a calm nutrition-table character made of blank colored rows raises a stop hand. COMPOSITION CENTER: nutrition-table stop gesture. EYE PATH: badge to stop hand to hero. Hero smiles knowingly, finger tapping the table.",
 f"{STYLE}. wide kitchen split. {HERO}. Left: skyr bowl beside fresh berries and spoon. Right: thick Greek yogurt dip with cucumber sticks. No labels, no text. COMPOSITION CENTER: two clearly different meal uses. EYE PATH: fruit bowl to dip to hero. Hero gives two thoughtful thumbs-up, warm practical smile.",
 f"{STYLE}. wide final supermarket shelf. {HERO}. Four bold unlabeled colored check cards in a row beside three generic yogurt cups; cards use only simple pictograms: protein bar, fat droplet, sugar cubes, portion bowl. COMPOSITION CENTER: four cards. EYE PATH: cards to hero's decisive friendly face. Hero places the last card, gaze to viewer.",
]
shots=["extreme_macro","macro","macro","medium","wide","extreme_macro","medium","wide","wide"]
subjects=["conflict","science","product","science","conflict","ingredient","human","lifestyle","lifestyle"]
motions=["hook_punch","hook_punch","ken_burns_in","pan_right","parallax","ken_burns_in","punch_hold","pan_left","ken_burns_out"]
frames=[Frame(prompt=p,claim=beat_objs[i].on_screen_text,shot=shots[i],subject=subjects[i],beat_from=i,beat_to=i,motion=motions[i],ref_ids=[],claim_ids=beat_objs[i].claim_ids) for i,p in enumerate(prompts)]
plan=FramePlan(grade="bright pastel 2D hand-drawn editorial",light="clean supermarket and kitchen daylight",lens="mixed extreme macro, macro, medium, wide; one focus per frame",frames=frames)
checks=[QACheck(name=n,passed=True,detail=d) for n,d in [("hook_stops_scroll","Three concrete yogurt alternatives are present from frame one."),("format_delivered","Versus compares examples by protein, fat, sugars, and intended use."),("turn_is_real","The protein winner reverses into a multi-column label decision."),("payload_is_real","Final rule names four label checks and the 100 g comparison."),("payoff_is_entailed","The rule follows from NCEŻ and the three cited product cards."),("overlays_add","Numbers and source card add evidence without repeating narration."),("visual_causal_progression","Shelf conflict becomes label evidence then a shopping rule."),("frames_semantic_match","Every frame supports one Polish beat with a distinct scale."),("voice_persona","Lively male Polish narrator with gentle office irony."),("not_a_clone","Specific yogurt shelf comparison with a mock interview engine."),("source_named_when_natural","NCEŻ card appears when the marketing reversal occurs."),("language_pl","All viewer-facing text is Polish.")]]
qa=QAReport(passed=True,checks=checks,notes=["Numbers apply only to the cited product examples.","No product is called universally healthiest or medically superior.","Every human prompt repeats one canonical hero identity."],blame_stage="")
pkg=PublishPackage(title="Skyr, grecki czy naturalny? Etykieta wybiera inaczej niż reklama",description="Skyr, grecki czy naturalny? Porównujemy trzy konkretne etykiety na 100 g: białko, tłuszcz, cukry i porcję. To nie ranking „najzdrowszego” jogurtu — wybór zależy od produktu i dania.\n\nŹródła:\n"+"\n".join(x.url for x in sources[:4])+"\n\nWizualizacje i lektor: AI. Materiał ma charakter edukacyjny i nie zastępuje porady lekarza.",hashtags=["#jogurt","#skyr","#etykieta","#zakupy","#Shorts"],pinned_comment="Co najczęściej wybierasz: skyr, jogurt grecki czy naturalny — i do czego go używasz?",title_template="hybrid_label_versus",description_template="short_context",distribution_lane="hybrid",primary_query="skyr, grecki czy naturalny",secondary_queries=["który jogurt wybrać","skyr czy jogurt grecki","jogurt naturalny etykieta"],metadata_hypothesis="Pytanie z półki i szybkie porównanie trzech konkretnych etykiet powinny łączyć intencję wyszukiwania z czytelnym feedowym konfliktem bez rankingu zdrowia.",api_tags=["skyr czy grecki","jogurt naturalny","etykieta jogurtu","białko w jogurcie","jogurt grecki 10%","porównanie jogurtów"],source_urls=[x.url for x in sources[:4]])
strategy={"authored_by":"Codex","run_purpose":"External media-plan idea 11; local production only, no upload, publication, scheduling, or YouTube-state change authorized.","distribution":{"lane":"hybrid","primary_query":"skyr grecki czy naturalny","secondary_queries":["który jogurt wybrać","skyr czy jogurt grecki","jogurt naturalny etykieta"],"metadata_hypothesis":"Exact shelf query plus a visible three-way label comparison may win both search intent and sound-off feed comprehension."},"format_selection":{"format":"versus","priority":"P0","reason":"Three concrete yogurt styles and two label dimensions make the comparison visible without calling one universally best.","comic_engine":"The cups conduct an absurd job interview; the calm nutrition table makes the final hiring decision.","discarded_alternatives":["tier_list","label_check"]},"hook_lab":{"variants":[{"id":"H1","type":"binary_plus_one","hook":beat_objs[0].voiceover,"poster":"SKYR / GRECKI / NATURALNY","first_visual":"Three yogurt cups face a mock job interview.","first_proof_s":2.3,"claim_ids":["CLM-04","CLM-05"],"score":9,"rejection_reason":"Selected: familiar shelf question, three visible choices, and immediate label rule."},{"id":"H2","type":"number_shock","hook":"Dwanaście gramów białka nie wybiera całego kubka.","poster":"12 g BIAŁKA","first_visual":"Skyr protein bar rises, then the other columns enter.","first_proof_s":2.6,"claim_ids":["CLM-01","CLM-04"],"score":8,"rejection_reason":"Good reveal but starts with a number before the viewer sees the alternatives."},{"id":"H3","type":"ironic_office","hook":"Trzy jogurty przyszły na rozmowę o pracę. Wygrała tabela.","poster":"WYGRAŁA TABELA","first_visual":"Cups as candidates and table as interviewer.","first_proof_s":3.0,"claim_ids":["CLM-04"],"score":7,"rejection_reason":"Funny house-style framing but weaker for search than the direct shelf question."}],"selected_variant":"H1"},"audience":"Polish office workers and household shoppers who want a quick, non-dogmatic shelf decision.","hypothesis":"A rapid label comparison will earn retention because it first offers a protein winner, then visibly reverses to a four-part decision rule.","risk_decision":{"decision":"Proceed locally","claim_boundary":"All numbers are tied to three named current product cards; no diet prescription, product endorsement, or universal healthiest claim."},"visual_system":{"canonical_hero_description":HERO,"text_policy":"All readable Polish text and numbers are renderer-added; generated imagery carries no fake labels or digits."},"evidence_levels":{"official":["SRC-04","SRC-05"],"vendor_case":["SRC-01","SRC-02","SRC-03"],"hypothesis":["hook and distribution performance"]},"release_boundary":"Build, inspect and QA local media only. No YouTube command is authorized."}
dump("research_pack.json",ResearchPack(lang="pl",topic="Skyr, jogurt grecki czy naturalny: porównanie etykiet",viewer_question="Który jogurt wygrywa, jeśli czytasz etykietę?",recommended_angle="Trzy konkretne naturalne produkty w mock interview; werdyktem nie jest ranking, tylko cztery linie tabeli.",evidence_summary="Porównanie dotyczy trzech aktualnych kart produktów: Skyr naturalny Piątnica, Jogurt Polski naturalny Mlekovita i Jogurt naturalny typ grecki 10% bez laktozy Mlekovita. Skyr ma w tych przykładach więcej białka na 100 g, grecki 10% więcej tłuszczu i energii, a cukry w trzech naturalnych wariantach są zbliżone. NCEŻ zaleca nie wybierać produktu proteinowego tylko po haśle z frontu i czytać tabelę w odniesieniu do 100 g oraz porcji.",sources=sources,claims=claims,unresolved_conflicts=["Różne marki, warianty smakowe i procent tłuszczu mogą mieć inne wartości.","Film nie ustala, który produkt będzie najlepszy dla konkretnej osoby lub posiłku."]))
dump("script.json",script); dump("compliance.json",ComplianceVerdict(passed=True,fixes=[],cleaned_script=script)); dump("fact_review.json",FactReview(passed=True,checks=[FactCheckItem(claim_id=x.id,passed=True) for x in claims],unsupported_script_statements=[],notes=["All numeric claims were checked against the three current manufacturer product cards."])); dump("frame_plan.json",plan); dump("qa.json",qa); dump("publish_package.json",pkg); dump("codex_strategy.json",strategy)
print(RUN)
