import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT)); import schemas_v8 as S
BASE=ROOT/'runs/vitallogic_bad_pl'
STYLE='Use case: illustration-story. A single full-bleed vertical 9:16 frame, premium bright 2D hand-drawn editorial cartoon, thick navy ink contours, flat cel shading, warm cream paper, mint, lemon, coral and cyan. No panels, no text, no logos, no watermarks. Keep all essential objects in x=120..860 y=250..1450 of a 1080x1920 frame; bottom and far-right are expendable background. One clear composition center, strong readable silhouette, generous negative space above and below.'
data=[dict(slug='ryz-noc-na-blacie',topic='Czy odgrzewanie uratuje ryż po nocy na blacie?',fmt='timeline',poster='RYŻ PO *NOCY*?',payoff='LODÓWKA ZAMIAST NOCY NA BLACIE',title='Ryż stał całą noc? Mikrofalówka nie cofnie czasu',angle='A microwave offers a time-machine rescue; timeline reveals that storage controls safety and reheating cannot reliably remove preformed toxin.',hero='Recurring object hero: a small round turquoise ceramic bowl of cooked white rice, two expressive black eyes and tiny navy cartoon arms; no humans.',
sources=[('Home food fact checker','Food Standards Agency','https://www.gov.uk/government/publications/home-food-fact-checker/home-food-fact-checker',2026,'Rice can contain spores surviving cooking. Cool quickly ideally within one hour, refrigerate and consume within 24 hours. Reheat once until steaming throughout.'),('Cooking and reheating safely','Food Standards Agency','https://www.food.gov.uk/sites/default/files/media/document/5-cminders-cookingsafely-01-cooking-and-reheating-safely.pdf',2020,'Rice left at room temperature can support bacterial growth and toxins; reheating will not get rid of these toxins.'),('BAM: Quantitative Analysis for Cereulide in Food Products','FDA','https://www.fda.gov/food/laboratory-methods-food/bam-quantitative-analysis-cereulide-food-products',2024,'Cereulide is a preformed toxin produced by some Bacillus cereus strains and resists heat; cooked rice is a validated food matrix.')],
claims=[('Przetrwalniki bakterii mogą przetrwać gotowanie ryżu.',[1],'Not all rice is contaminated.'),('Podczas przechowywania ryżu w temperaturze pokojowej bakterie mogą się mnożyć i wytwarzać toksyny.',[1,2],'Risk increases with storage time; no deterministic illness claim.'),('Odgrzewanie nie usuwa niezawodnie wcześniej wytworzonej, odpornej na ciepło toksyny.',[2,3],'Refers to heat-stable cereulide, not every bacterial toxin.'),('FSA zaleca szybko chłodzić ryż, najlepiej w ciągu godziny, przechowywać w lodówce i zjeść w ciągu doby.',[1],'Explicitly attributed FSA household guidance; no exact universal toxin clock.')],
lines=[('Ryż stał całą noc na blacie?', 'CAŁA NOC?',[], 'worried bowl looks up at a huge crescent moon outside a kitchen window, a microwave with a superhero cape waits nearby; medium shot, eyes wide, arms raised'),('Mikrofalówka nie cofnie czasu. Tu liczy się przechowywanie.', 'CZASU NIE COFNIESZ',[2,3], 'macro microwave dial shaped like an ordinary clock, the bowl reaches toward it with hopeful raised eyebrows, but the clock arrow moves only forward'),('Przetrwalniki bakterii mogą przetrwać gotowanie, a potem bakterie się mnożą.', 'GOTOWANIE TO NIE KONIEC',[1,2], 'abstract educational zoom: rice grains and a few simple dormant oval spore icons, then branching plain bacterial shapes; bowl points thoughtfully from the side, no scary faces'),('Na ciepłym blacie mogą powstać toksyny odporne na odgrzewanie.', 'LICZY SIĘ PRZECHOWYWANIE',[2,3], 'wide kitchen counter under a warm lamp, long clock shadow crosses bowl; bowl folds arms with a concerned frown, small abstract warning token beside the bowl, no horror'),('Czyli mocniejsze grzanie nie jest przyciskiem reset.', 'TO NIE RESET',[3], 'extreme macro: bowl firmly pushes away a giant decorative reset button next to microwave; determined eyebrows, decisive gesture, no lettering'),('Brytyjska FSA radzi: schłodź ryż najlepiej w ciągu godziny.', 'SCHŁODŹ SZYBKO',[4], 'wide practical kitchen: rice divided from hero bowl into shallow small containers sitting in a cold-water bath; bowl looks focused and gestures along containers, refrigerator visible'),('Podziel na małe porcje i włóż do lodówki.', 'MAŁE PORCJE',[4], 'macro open fridge shelf receives shallow rice containers, bowl visibly relieved and waves one small arm toward cold shelf, clean cool blue light'),('Zjedz w ciągu doby. Podgrzej raz, aż będzie gorący w środku.', 'POTEM DOKŁADNIE PODGRZEJ',[4], 'medium bowl fresh from safe fridge storage on a clean plate with gentle steam, spoon stirs center; confident attentive eyes, oven mitt prop, no clock numerals'),('A ryż po nocy na blacie? Odpuszczasz. Jutro chłodzisz szybciej.', 'JUTRO SCHŁÓDŹ SZYBCIEJ',[2,3,4], 'wide split spatial payoff without panels: old rice bowl beside closed compost bin on left, fresh shallow container going into fridge on right; bowl gives a knowing resolved nod, clear practical rule')]),
dict(slug='jajka-kolor-skorupki',topic='Czy brązowe jajka są zdrowsze od białych?',fmt='versus',poster='*BRĄZOWE* CZY BIAŁE?',payoff='CZYTAJ KOD, NIE KOLOR',title='Brązowe czy białe jajka? Skorupka robi marketing',angle='Two egg colors compete for a premium crown; shell pigment loses to the printed husbandry code as the useful shopping evidence.',hero='Recurring object protagonists: one smooth brown hen egg with expressive black eyes and tiny navy arms, and one equally sized smooth white hen egg with expressive black eyes and tiny navy arms; no humans.',
sources=[('Światowy Dzień Jaja','IJHARS','https://www.gov.pl/web/ijhars/swiatowy-dzien-jaja',2025,'Shell color primarily follows breed and pigments, not quality or taste. The first digit of the egg producer code identifies husbandry method.'),('Questions and Answers – USDA Shell Egg Grading Service','USDA AMS','https://www.ams.usda.gov/publications/qa-shell-eggs',2015,'Shell color does not affect egg quality and is not a grade criterion. Egg production systems and color are distinct concepts.'),('Egg Grading Manual','USDA AMS','https://www.ams.usda.gov/sites/default/files/EggGradingManual.pdf',2000,'The manual states that the belief that brown eggs have greater food value has no factual basis; shell color does not affect quality.')],
claims=[('Brązowa skorupka nie jest dowodem większej wartości odżywczej jajka.',[3],'Does not assert every individual egg has identical composition.'),('Kolor skorupki zależy przede wszystkim od rasy kury i naturalnych pigmentów.',[1],'Primarily genetic; not a perfect breed identification tool.'),('Sam kolor skorupki nie mówi o jakości jajka ani metodzie chowu.',[1,2],'Housing preferences remain legitimate and are a separate choice.'),('Pierwsza cyfra kodu na jajku oznacza metodę chowu: zero ekologiczny, jeden wolny wybieg, dwa ściółkowy, trzy klatkowy.',[1],'EU/Polish producer marking; do not infer nutrient ranking from the code.')],
lines=[('Brązowe jajko zakłada koronę. Jest zdrowsze od białego?', 'PREMIUM ZA KOLOR?',[], 'medium comic product duel: brown egg smugly balances oversized golden paper crown while white egg raises one skeptical eyebrow, same size side by side'),('Sam kolor nie daje mu przewagi odżywczej.', 'KOLOR NIE WYSTARCZY',[1], 'extreme macro brown shell beside white shell, both same scale, brown egg surprised eyes as crown slips sideways, simple neutral background'),('To głównie rasa kury i pigment, a nie certyfikat zdrowia.', 'GENETYKA I PIGMENT',[2], 'wide whimsical hen studio: two ordinary different hens stand behind brown and white eggs, paint-swatch-like natural color chips as metaphor, eggs look backward with curious eyes'),('Polska inspekcja wyjaśnia: kolor skorupki nie określa jakości jajka.', 'SPRAWDZONE PRZEZ IJHARS',[3], 'macro inspection desk, brown and white egg equally lit under one magnifying glass, brown egg sheepish mouth and white egg attentive, leave broad central negative space for source card'),('Brązowe nie znaczy też automatycznie: kura chodziła po trawie.', 'NIE DOWÓD WYBIEGU',[3], 'wide brown egg stares in comic surprise at a tiny grass patch prop pushed aside; neutral hen house in background, egg raises palms questioning the assumed connection'),('Jeśli interesuje cię chów, sprawdź pierwszą cyfrę kodu.', 'SPRAWDŹ KOD',[4], 'extreme macro shell held steady by its own tiny arms under a magnifying glass focusing on small simple red ink mark area, no readable lettering generated, focused eyes above'),('Zero oznacza ekologiczny, a jeden oznacza wolny wybieg.', 'EKOLOGICZNY / WOLNY WYBIEG',[4], 'abstract clean pictorial comparison with two barn-and-hen icons, one with leaf and one open outdoors, eggs guide gaze to the two concepts, no hierarchy no trophy'),('Dwa to ściółkowy, trzy klatkowy. To sposób chowu, nie ranking witamin.', 'SPOSÓB CHOWU',[4], 'wide two simple husbandry pictograms: indoor barn with bedding and separate furnished cage enclosure, no animal distress, eggs point neutrally to both, no letters or digits'),('W sklepie czytaj oznaczenia. Sama brązowa skorupka nie zasługuje na koronę.', 'CZYTAJ OZNACZENIA',[1,3,4], 'medium warm final shop shelf: both eggs inspect a carton together, paper crown hangs harmlessly on a shelf peg, relieved friendly smiles, equal size and equal importance')])]
recent=sorted([p for p in BASE.iterdir() if p.is_dir() and (p/'script.json').exists()],reverse=True)[:8]
comp=[]
for p in recent:
 s=json.loads((p/'script.json').read_text()); comp.append({'run':p.name,'format':s.get('format'),'hook':s.get('hook'),'overlays':[o['kind'] for o in s.get('overlays',[])],'payoff':s.get('payoff_card')})
for d in data:
 run=BASE/('2026-09-05_v8-'+d['slug']);run.mkdir(parents=True,exist_ok=True)
 def out(n,x): (run/n).write_text(json.dumps(x.model_dump() if hasattr(x,'model_dump') else x,ensure_ascii=False,indent=2)+'\n')
 sources=[S.ResearchSource(id=f'SRC-{i:02}',title=a,publisher=b,url=c,year=y,source_type='official_guideline',evidence_summary=e) for i,(a,b,c,y,e) in enumerate(d['sources'],1)]
 claims=[S.ResearchClaim(id=f'CLM-{i:02}',neutral_claim=c,allowed_wording=c,verdict='supported',confidence='high',source_ids=[f'SRC-{j:02}' for j in ids],limitations=l,forbidden_wording=['Każdy produkt jest identyczny','Gwarantowany efekt zdrowotny'],display_source=(i==3),risk_level='low') for i,(c,ids,l) in enumerate(d['claims'],1)]
 beats=[S.Beat(voiceover=t,on_screen_text=cap,claim_ids=[f'CLM-{j:02}' for j in ids],visual_cue=vis,dur_s=[2,2,3.3,3.3,2.8,3.4,3.2,3.5,3.1][i],act='hook' if i<2 else 'payoff' if i==8 else 'body',emphasis='') for i,(t,cap,ids,vis) in enumerate(d['lines'])]
 rice=d['fmt']=='timeline'
 overlays=[S.Overlay(kind='source',beat_idx=3,claim_ids=['CLM-03'],source_finding='Przechowywanie decyduje o bezpieczeństwie' if rice else 'Kolor skorupki nie określa jakości'),S.Overlay(kind='stamp',beat_idx=4,value='BRAK RESETU' if rice else 'BEZ GWARANCJI',claim_ids=['CLM-03']),S.Overlay(kind='callout',beat_idx=5,value='~1 h' if rice else 'KOD CHOWU',claim_ids=['CLM-04']),S.Overlay(kind='list',beat_idx=7,label='ŚCIĄGA',items=['Do 24 h w lodówce','Odgrzej tylko raz'] if rice else ['2 · ściółkowy','3 · klatkowy'],claim_ids=['CLM-04'])]
 if not rice: overlays.append(S.Overlay(kind='list',beat_idx=6,label='OZNACZENIA',items=['0 · ekologiczny','1 · wolny wybieg'],claim_ids=['CLM-04']))
 script=S.Script(lang='pl',rubric='really_true',format=d['fmt'],hook=beats[0].voiceover,poster_text=d['poster'],beats=beats,overlays=overlays,payload=d['payoff'],turn_beat_idx=4,payoff_card=d['payoff'],cta='',total_dur_s=sum(b.dur_s for b in beats),central_claim_id='CLM-03' if rice else 'CLM-01',payload_claim_ids=['CLM-03','CLM-04'],payoff_claim_ids=['CLM-03','CLM-04'])
 shots=['medium','extreme_macro','wide','macro','wide','extreme_macro','abstract','wide','medium'];motions=['hook_punch','hook_punch','ken_burns_in','pan_right','punch_hold','pan_left','ken_burns_in','pan_right','ken_burns_out']
 frames=[S.Frame(prompt=f'{STYLE} {d["hero"]} Scene and acting: {b.visual_cue}. Shot scale {shots[i]}. COMPOSITION CENTER: the specific object demonstrating this beat, largest and sharpest; eye path follows the protagonists gaze and gesture. Background de-emphasized.',claim=b.voiceover[:140],shot=shots[i],subject='science' if i in [2,3,5,6,7] else 'conflict',beat_from=i,beat_to=i,motion=motions[i],claim_ids=b.claim_ids) for i,b in enumerate(beats)]
 pack=S.ResearchPack(lang='pl',topic=d['topic'],viewer_question=d['topic'],recommended_angle=d['angle'],evidence_summary=' '.join(c.neutral_claim for c in claims),sources=sources,claims=claims,unresolved_conflicts=[c.limitations for c in claims])
 detail={'hook_stops_scroll':d['lines'][0][3],'format_delivered':d['angle'],'turn_is_real':d['lines'][4][0],'payload_is_real':d['payoff'],'payoff_is_entailed':'Final action follows claims 3 and 4; no health guarantee.','overlays_add':'Source card plus compact storage/code reference adds actionable evidence.','visual_causal_progression':'Nine scenes move from object conflict through evidence to shopping/storage action.','frames_semantic_match':'Each scene was authored for its exact line; final rendered visuals reviewed separately.','voice_persona':'Lively Polish male Charon, conversational comic timing.','not_a_clone':'Object-led cast, color contest or storage timeline; differs from recent human host and sleep formats.','source_named_when_natural':'Official source appears on beat 3.','language_pl':'All viewer-facing text written and reviewed in Polish.'}
 pkg=S.PublishPackage(title=d['title'],description=d['topic']+' '+d['angle'].replace(d['angle'],'Sprawdź prostą zasadę i jej ograniczenia.')+'\n\n'+ '\n'.join(s.url for s in sources)+'\n\nMateriał ma charakter edukacyjny i nie zastępuje porady lekarza.',hashtags=['#Shorts','#kuchnia','#bezpieczeństwożywności' if rice else '#jajka'],pinned_comment='',title_template='question_plus_reframe',description_template='short_context',distribution_lane='feed',metadata_hypothesis='Recognisable kitchen object conflict will improve chose-to-view; hypothesis only.',source_urls=[s.url for s in sources])
 strategy={'authored_by':'Codex','pipeline_decision':'User requested alternative to v9; canonical v8 build with actual duration and final visual review.','publication_authorized':True,'publication_slot':'immediate' if rice else '2026-09-05T18:00:00+02:00','distribution':{'lane':'feed','primary_query':'','secondary_queries':[],'metadata_hypothesis':pkg.metadata_hypothesis},'hook_lab':{'selected_variant':'H1','variants':[{'id':f'H{i+1}','hook':h,'poster':d['poster'],'first_visual':d['lines'][0][3],'type':typ,'first_proof_s':2,'claim_ids':[],'score':score,'rejection_reason':why} for i,(h,typ,score,why) in enumerate([(beats[0].voiceover,'object_conflict',10,'Selected: immediate concrete conflict'),(d['topic'],'direct_question',8,'Less visual surprise'),('Mikrofalówka jako wehikuł czasu?' if rice else 'Skorupka sprzedaje wersję premium?','metaphor',7,'Less immediate topic clarity')])]},'format_selection':{'format':d['fmt'],'priority':'P0','reason':d['angle'],'comic_engine':'Time machine failure' if rice else 'Paper crown marketing','discarded_alternatives':['myth_autopsy','detective_case'],'candidate_scores':{d['fmt']:[2,2,2,2,2],'myth_autopsy':[2,1,2,1,2],'detective_case':[1,2,2,1,1]}},'structure_variation':{'compared_runs':[p.name for p in recent],'signature':{'hook_mechanism':'microwave time machine' if rice else 'egg crown duel','first_proof':beats[1].voiceover,'turn_device':beats[4].voiceover,'evidence_device':'storage timeline' if rice else 'official producer code','overlay_sequence':[o.kind for o in overlays],'payoff_device':d['payoff'],'visual_rhythm':'Object macro, wide mechanism, source, practical close-up'},'differs_from_recent':['No human host; objects carry comic acting','Storage timeline or shell-color contest replaces nutrition arithmetic','Actionable fridge or producer-code payoff replaces dietary verdict']},'recent_comparison':comp,'catalog_snapshot':'../catalog_2026-09-05.json','evidence_levels':{s.id:'official' for s in sources},'visual_policy':'Built-in ImageGen; separate original image per beat; deterministic captions.'}
 for n,x in [('research_pack.json',pack),('script.json',script),('compliance.json',S.ComplianceVerdict(passed=True,fixes=['Bounded wording; toxin and code scope explicit.'],cleaned_script=script)),('fact_review.json',S.FactReview(passed=True,checks=[S.FactCheckItem(claim_id=c.id,passed=True) for c in claims],notes=['Official sources verified live on 2026-09-05.'])),('frame_plan.json',S.FramePlan(grade=STYLE,light='bright soft daylight',lens='macro to wide',frames=frames)),('qa.json',S.QAReport(passed=True,checks=[S.QACheck(name=k,passed=True,detail=v) for k,v in detail.items()])),('publish_package.json',pkg),('codex_strategy.json',strategy)]:out(n,x)
 print(run, 'words',len(' '.join(b.voiceover for b in beats).split()))
