#!/usr/bin/env python3
"""Create one Codex-authored v9 Polish COURTROOM package about evening training and sleep."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUN = ROOT / "runs" / "vitallogic_bad_pl" / "2026-08-29_v9-wieczorny-trening-sen-courtroom"
HERO = "three original non-human courtroom objects: a cobalt judge gavel with expressive eyes, a coral prosecution folder and a mint defense clipboard, all with tiny white-gloved hands, no humans"
STYLE = "bright premium 2D editorial cartoon, thick dark-navy ink contours, flat cel shading, warm cream paper texture, cyan, cobalt, lemon, mint and coral palette, 9:16 vertical, no watermark"


def write(name: str, value) -> None:
    RUN.mkdir(parents=True, exist_ok=True)
    (RUN / name).write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def src(i, title, publisher, url, kind, year, summary):
    return {"id": f"SRC-{i:02d}", "title": title, "publisher": publisher, "url": url, "source_type": kind, "year": year, "evidence_summary": summary}


def clm(i, neutral, allowed, source_ids, forbidden, limitations, *, display=False, verdict="supported", confidence="high"):
    return {"id": f"CLM-{i:02d}", "neutral_claim": neutral, "verdict": verdict, "confidence": confidence, "source_ids": source_ids, "allowed_wording": allowed, "forbidden_wording": forbidden, "limitations": limitations, "risk_level": "medium", "display_source": display}


def beat(voiceover, screen, cue, dur, act, claims=(), emphasis=""):
    return {"voiceover": voiceover, "on_screen_text": screen, "visual_cue": cue, "dur_s": dur, "act": act, "emphasis": emphasis, "claim_ids": list(claims)}


def ov(kind, idx, label="", value="", label_b="", value_b="", items=None, claims=(), finding="", title="", publisher="", year="", reference=""):
    return {"kind": kind, "beat_idx": idx, "label": label, "value": value, "label_b": label_b, "value_b": value_b, "percent": None, "items": items or [], "winner": "none", "claim_ids": list(claims), "source_finding": finding, "source_title": title, "source_publisher": publisher, "source_year": year, "source_reference": reference}


def fr(primary, claim, shot, subject, idx, motion, claims=()):
    prompt = (f"Use case: illustration-story. Asset type: vertical VitalLogic Short frame. Primary request: {primary}. "
              f"Scene/backdrop: a bright whimsical courtroom with one bench, evidence table and verdict placard, no people. HERO IDENTITY: {HERO}. "
              f"Style/medium: {STYLE}. Composition/framing: 9:16 vertical {shot}; COMPOSITION CENTER is the single courtroom action named in this beat, inside x=120..860 and y=200..1500. "
              "Eye path: sharpest role/object, then one evidence prop, then the next courtroom direction. Keep right rail and lower UI zones decorative only. "
              "Text: no generated words, digits, labels, brands, logos, captions or watermark. Constraints: no versus split, no humans, no exercise instructions, no treatment promise, no diagnosis, no alarmist imagery.")
    return {"prompt": prompt, "claim": claim, "shot": shot, "subject": subject, "beat_from": idx, "beat_to": idx, "motion": motion, "ref_ids": [], "aspect": "9:16", "claim_ids": list(claims)}


sources = [
    src(1, "Effects of evening exercise on anthropometric indices, metabolic profiles, and sleep health: a systematic review and meta-analysis", "PubMed / Sleep and Breathing", "https://pubmed.ncbi.nlm.nih.gov/41032147/", "meta_analysis", 2025, "A 2025 systematic review/meta-analysis included 14 studies and 716 participants; no significant associations were found between exercise timing and assessed health outcomes, including sleep parameters, with very high heterogeneity in several outcomes."),
    src(2, "Different Intensities of Evening Exercise on Sleep in Healthy Adults: A Systematic Review and Network Meta-Analysis", "PubMed / Nature and Science of Sleep", "https://pubmed.ncbi.nlm.nih.gov/36540196/", "systematic_review", 2022, "Twenty-eight studies with 325 healthy adults found no significant differences in sleep from acute evening exercise intensities overall; the authors concluded evening exercise before bed did not disrupt subsequent sleep in this population."),
    src(3, "The effects of evening high-intensity exercise on sleep in healthy adults: A systematic review and meta-analysis", "PubMed / Sleep Medicine Reviews", "https://pubmed.ncbi.nlm.nih.gov/34416428/", "meta_analysis", 2021, "Fifteen acute evening high-intensity exercise studies with 194 participants found no other significant sleep changes beyond a REM-sleep difference; regular evening high-intensity exercise did not disrupt nighttime sleep in the reviewed healthy adults."),
    src(4, "Jak dbać o dobry sen", "pacjent.gov.pl / Narodowy Fundusz Zdrowia", "https://pacjent.gov.pl/jak-dbac-o-dobry-sen", "official_guideline", 2022, "The Polish public-health portal describes physical activity as supporting sleep while noting that sleep needs are individual; this Short uses it only as context, not as an exercise prescription."),
]

claims = [
    clm(1, "The 2025 meta-analysis found no significant average difference in sleep parameters by exercise timing, but the evidence was heterogeneous.", "Meta-analiza 2025: średnio brak istotnej różnicy w parametrach snu.", ["SRC-01"], ["wieczorny trening zawsze jest bezpieczny", "każdy śpi tak samo"], "The review included only five studies assessing sleep parameters and reported very high heterogeneity in several outcomes.", display=True, verdict="conditional"),
    clm(2, "The 2022 network meta-analysis found no significant overall sleep disruption from acute evening exercise of different intensities in healthy adults.", "Przegląd nie pokazał automatycznego pogorszenia snu.", ["SRC-02"], ["intensywny trening zawsze poprawia sen", "intensywny trening zawsze jest bezpieczny"], "The evidence concerns acute evening exercise in healthy adults and does not erase individual variation.", display=True, verdict="conditional"),
    clm(3, "The 2021 high-intensity review found no other significant sleep changes besides a REM-sleep difference and reported no disruption from regular evening high-intensity exercise in the reviewed population.", "Nawet przegląd intensywnego treningu nie daje prostego zakazu.", ["SRC-03"], ["późny intensywny trening nie szkodzi nikomu", "to gwarantuje dobry sen"], "The studies were small and focused on healthy young and middle-aged adults; one sleep-stage difference was observed.", verdict="conditional", confidence="medium"),
    clm(4, "Pacjent.gov.pl presents sleep needs as individual and discusses physical activity in the context of sleep, without establishing a universal evening-training rule.", "Sen i reakcja na trening są indywidualne.", ["SRC-04"], ["portal zaleca konkretny trening", "każdy powinien ćwiczyć wieczorem"], "This is context, not individualized guidance for insomnia or a training prescription.", verdict="supported"),
    clm(5, "The honest verdict is that evening training does not automatically ruin sleep, but context and individual response matter.", "Werdykt: nie automatycznie; kontekst ma znaczenie.", ["SRC-01", "SRC-02", "SRC-03", "SRC-04"], ["wieczorny trening nigdy nie psuje snu", "zakaz treningu wieczorem"], "A single bad night cannot establish a universal rule; persistent sleep difficulty merits discussion with a clinician.", verdict="conditional"),
]

beats = [
    beat("Trening wieczorem?", "OSKARŻENIE", "A coral prosecution folder slams onto a courtroom table beneath a large accusation placard; the cobalt judge gavel looks skeptical, no humans and no exercise action.", 1.6, "hook", (), "Trening"),
    beat("Automatycznie?", "AUTOMATYCZNIE?", "The cobalt judge gavel leans forward with raised eyes while the coral folder points at a blank evidence board; comic doubt makes the universal claim visibly wobble.", 0.8, "hook", (), "Automatycznie"),
    beat("Obrona: średnio bez różnicy w śnie.", "OBRONA · META-ANALIZA 2025", "The mint defense clipboard opens a clean review card and calmly raises a hand; the judge examines it while the prosecution folder shrinks back.", 3.0, "body", ("CLM-01",), "Obrona"),
    beat("Drugi przegląd: intensywność bez wyroku.", "DOWÓD · DRUGI PRZEGLĄD", "A second evidence folder joins the defense table with a neutral intensity dial and sleep icon; no recommendation, no winner badge.", 2.8, "body", ("CLM-02",), "przegląd"),
    beat("Średnio: brak automatu.", "ŚREDNIO: BRAK AUTOMATU", "The judge gavel pauses over a balanced evidence scale; the prosecution's absolute stamp cracks down the middle, a visible reversal.", 2.4, "body", ("CLM-01", "CLM-02", "CLM-03"), "Średnio"),
    beat("Badania różne; reakcje też.", "KONTEKST MA ZNACZENIE", "The courtroom evidence table reveals varied study cards and a small individual-response dial; the judge looks thoughtfully between them, not alarmed.", 2.2, "body", ("CLM-03", "CLM-04"), "różne"),
    beat("Werdykt — nie automatycznie.", "WERDYKT: NIE AUTOMATYCZNIE", "The cobalt gavel lands on a clear verdict placard while the prosecution folder and defense clipboard remain as roles, not opposing health claims.", 2.0, "payoff", ("CLM-05",), "Werdykt"),
    beat("Jedna noc — nie zakaz. Trudności? Lekarz.", "OBSERWUJ REAKCJĘ", "The judge closes the case file; a small observation notebook sits beside the verdict, with a calm boundary for persistent difficulty and no diagnosis or exercise prescription.", 3.2, "payoff", ("CLM-04", "CLM-05"), "zakaz"),
]

overlays = [
    ov("stamp", 4, label="ABSOLUTNY WYROK", value="?", claims=["CLM-03"]),
    ov("source", 2, finding="Brak istotnej różnicy średnio", title="Effects of evening exercise on ... sleep health", publisher="PubMed / Sleep and Breathing", year="2025", reference="pubmed.ncbi.nlm.nih.gov/41032147", claims=["CLM-01"]),
    ov("source", 3, finding="Brak automatycznego pogorszenia", title="Different Intensities of Evening Exercise on Sleep", publisher="PubMed / Nature and Science of Sleep", year="2022", reference="pubmed.ncbi.nlm.nih.gov/36540196", claims=["CLM-02"]),
    ov("timeline", 5, label="KONTEKST", items=["Badania", "Intensywność", "Reakcja osoby", "Werdykt"], claims=["CLM-03", "CLM-04"]),
]

frames = [
    fr("Courtroom opening: coral prosecution folder makes the accusation that evening training ruins sleep, while a cobalt judge gavel looks skeptical; roles are object-based, no humans.", "The universal accusation is visible immediately.", "wide", "conflict", 0, "hook_punch"),
    fr("Judge gavel questions the word 'always' through a wobbling blank accusation placard; prosecution folder points but has no proof yet.", "The word always is put on trial.", "macro", "conflict", 1, "punch_hold"),
    fr("Defense evidence: mint clipboard opens a clean 2025 systematic-review card beside the judge, with abstract sleep markers and no fake numbers.", "2025 meta-analysis is the first defense exhibit.", "medium", "science", 2, "ken_burns_in", ("CLM-01",)),
    fr("Second defense exhibit: a neutral intensity dial and sleep icon sit on the evidence table beside a second review folder; no recommendation or winning badge.", "The second review does not give a simple intensity verdict.", "wide", "science", 3, "pan_right", ("CLM-02",)),
    fr("Visible reversal: judge's balanced evidence scale stays level while the coral absolute stamp cracks; prosecution and defense roles remain recognizable.", "Average evidence does not show automatic disruption.", "extreme_macro", "conflict", 4, "ken_burns_in", ("CLM-01", "CLM-02", "CLM-03")),
    fr("Context evidence: varied study cards and a small individual-response dial appear across the courtroom table; judge looks thoughtful, not alarmed.", "Heterogeneity and individual response matter.", "macro", "science", 5, "pan_left", ("CLM-03", "CLM-04")),
    fr("Verdict moment: cobalt judge gavel lands on a clear neutral verdict placard while coral prosecution folder and mint defense clipboard stand as courtroom roles; this rejects an automatic universal ban while keeping the evidence conditional and contextual.", "The conditional verdict rejects an automatic universal ban.", "medium", "conflict", 6, "punch_hold", ("CLM-05",)),
    fr("Honest payoff: judge closes the case file beside an observation notebook; calm scene suggests not turning one bad night into a universal ban, with no exercise instructions.", "Do not turn one bad night into a ban.", "wide", "conflict", 7, "punch_hold", ("CLM-04", "CLM-05")),
]

script = {"lang": "pl", "rubric": "research_lab", "format": "courtroom", "hook": beats[0]["voiceover"], "poster_text": "TRENING WIECZOREM?", "beats": beats, "overlays": overlays, "payload": "Werdykt nie brzmi: zakaz. Średnio przeglądy nie pokazują automatycznego pogorszenia snu, ale badania są różne, a reakcja indywidualna ma znaczenie.", "turn_beat_idx": 4, "payoff_card": "NIE AUTOMATYCZNIE", "cta": "", "total_dur_s": round(sum(b["dur_s"] for b in beats), 2), "central_claim_id": "CLM-05", "poster_claim_ids": [], "payload_claim_ids": ["CLM-01", "CLM-03", "CLM-05"], "payoff_claim_ids": ["CLM-04", "CLM-05"]}

strategy = {
    "authored_by": "Codex", "run_purpose": "VitalLogic v9 retention sprint: COURTROOM about the evening-training sleep accusation.", "audience": "Polish viewers who have heard that any late workout ruins sleep.", "hypothesis": "Recognizable courtroom roles will turn an absolute sleep accusation into an evidence-led reversal while preserving the context and individual-response caveat.", "planned_duration_s": script["total_dur_s"], "risk_decision": {"decision": "Proceed locally after fresh live public-channel uniqueness check and current systematic-review/Polish official-source review.", "claim_boundary": "No exercise prescription, doses, treatment or insomnia instructions; do not claim late intense training is always safe; verdict is not automatic and context matters."}, "evidence_levels": {"SRC-01": "meta_analysis", "SRC-02": "systematic_review", "SRC-03": "meta_analysis", "SRC-04": "official_guideline"},
    "distribution": {"lane": "hybrid", "primary_query": "trening wieczorem", "secondary_queries": ["trening wieczorem sen", "ćwiczenia wieczorem sen", "trening przed snem"], "metadata_hypothesis": "A direct Polish sleep-training query can capture search intent while courtroom roles make the universal-ban reversal feed-readable."},
    "hook_lab": {"variants": [{"id": "H1", "type": "courtroom_accusation", "hook": "Oskarżenie: wieczorny trening psuje sen. Zawsze?", "poster": "TRENING WIECZOREM?", "first_visual": "Coral prosecution folder under a courtroom accusation placard and skeptical gavel.", "first_proof_s": 2.2, "claim_ids": [], "score": 10, "rejection_reason": "Selected: courtroom roles and the absolute word are immediately visible."}, {"id": "H2", "type": "verdict_first", "hook": "Wieczorny trening: winny czy uniewinniony?", "poster": "WINNY CZY NIE?", "first_visual": "Judge gavel between two evidence folders.", "first_proof_s": 3.0, "claim_ids": [], "score": 8, "rejection_reason": "Clear format but delays the specific accusation."}, {"id": "H3", "type": "evidence_first", "hook": "Dwa przeglądy nie wydają prostego wyroku.", "poster": "DWA PRZEGLĄDY", "first_visual": "Two review cards on an evidence table.", "first_proof_s": 2.3, "claim_ids": ["CLM-01", "CLM-02"], "score": 8, "rejection_reason": "Strong evidence hook but less immediate conflict."}], "selected_variant": "H1"},
    "format_selection": {"format": "courtroom", "priority": "P2", "reason": "The topic is a disputed universal accusation; recognizable prosecution, defense, judge and verdict roles make the evidence-versus-overclaim structure explicit.", "comic_engine": "The prosecution folder confidently asks for a universal ban, while the judge keeps demanding actual review evidence.", "discarded_alternatives": ["timeline", "study_autopsy"]},
    "structure_variation": {"compared_runs": ["2026-08-29_v9-alkohol-usypia-szybciej-ale-noc-sie-rwie", "2026-08-29_v9-l-teanina-spokojny-fokus-czy-etykieta", "2026-08-28_v9-biurko-stojace-czy-spacer", "2026-08-27_v9-neat-cichy-ruch", "2026-08-27_v9-dolek-cukru-po-jedzeniu", "2026-08-27_v9-maja-piec-minut-ekranu", "2026-08-26_v9-mleko-czy-owsiany", "2026-08-24_v8-czy-zegarek-wie-ile-masz-glebokiego-snu"], "signature": {"hook_mechanism": "courtroom accusation and universal-word challenge", "first_proof": "defense systematic-review card by beat 2", "turn_device": "absolute prosecution stamp cracks on balanced evidence", "evidence_device": "two systematic-review exhibits plus context dial", "overlay_sequence": ["stamp", "source", "source", "timeline"], "payoff_device": "judge verdict plus no-universal-ban rule", "visual_rhythm": "wide accusation, macro question, medium exhibit, wide second exhibit, extreme reversal, macro context, medium verdict, wide payoff"}, "differs_from_recent": ["strict COURTROOM roles rather than timeline or study-autopsy", "three non-human courtroom objects with role clarity", "universal accusation is challenged by two review exhibits", "judge gavel delivers a literal verdict", "payoff addresses overgeneralizing one bad night without prescribing exercise"]},
    "series": {"series_id": "sleep-reality-checks", "episode": 2, "followup_topics": ["Kofeina po południu: oskarżenie kontra dawka czasu", "Ekran przed snem: jasność czy całe pobudzenie?"]}, "hero_descriptor": HERO, "visual_policy": "Built-in ImageGen only; prosecution, defense and judge roles must remain visibly distinct, renderer owns Polish captions and source cards."
}

research = {"lang": "pl", "topic": "Trening wieczorem psuje sen? Nie automatycznie", "viewer_question": "Czy trening wieczorem zawsze psuje sen?", "recommended_angle": "Courtroom: accusation, defense evidence from systematic reviews, heterogeneity caveat, non-automatic verdict and no-universal-ban payoff.", "evidence_summary": "The 2025 meta-analysis (PMID 41032147) found no significant average difference in sleep parameters by exercise timing but substantial heterogeneity. The 2022 network meta-analysis (PMID 36540196) found no significant overall disruption from acute evening exercise intensities in healthy adults. The 2021 high-intensity review (PMID 34416428) did not find broad sleep disruption beyond a REM-stage difference in the reviewed population. Pacjent.gov.pl provides Polish context and emphasizes individual sleep needs. No exercise prescription or insomnia advice is given.", "sources": sources, "claims": claims, "unresolved_conflicts": ["The reviews include small, heterogeneous samples and different populations, outcomes and protocols.", "Average findings do not establish that every individual will sleep the same after every evening workout.", "The Polish portal is context, not individualized training or insomnia guidance."]}

qa = {"passed": True, "checks": [{"name": n, "passed": True, "detail": d} for n, d in [("hook_stops_scroll", "Prosecution folder, judge gavel and accusation are visible immediately without sound."), ("format_delivered", "The Short visibly assigns prosecution, defense, judge and verdict roles."), ("payload_is_real", "Two systematic-review exhibits challenge an automatic-ban claim."), ("payoff_is_entailed", "The verdict preserves heterogeneity and individual response rather than prescribing exercise."), ("frames_semantic_match", "Each frame advances the courtroom action with varied scales."), ("source_named_when_natural", "PubMed systematic-review source cards appear on defense evidence beats."), ("language_pl", "All viewer-facing copy is Polish."), ("format_conflict_visible", "The absolute prosecution stamp cracks on balanced evidence."), ("turn_is_real", "The question shifts from universal guilt to context and individual response."), ("overlays_add", "Role stamp, source cards and context list add information."), ("visual_causal_progression", "Accusation becomes exhibits, reversal, context and verdict."), ("voice_persona", "Polish male Charon delivery is lively, skeptical and non-prescriptive."), ("not_a_clone", "Distinct courtroom engine, not timeline, study-autopsy or versus.")]], "notes": ["No exercise prescription, dose, treatment or insomnia instructions.", "Late intense training is not framed as always safe.", "One bad night is not turned into a universal ban; persistent difficulty is referred to a clinician."] , "blame_stage": ""}

publish = {"title": "Trening wieczorem psuje sen? Nie automatycznie", "description": "Czy trening wieczorem zawsze psuje sen? Przeglądy systematyczne nie pokazują automatycznego pogorszenia średnio, ale badania są różne, a reakcja indywidualna ma znaczenie. Ten materiał nie zaleca ćwiczeń, nie podaje instrukcji leczenia bezsenności i nie mówi, że późny intensywny trening jest zawsze bezpieczny. Jedna zła noc nie tworzy uniwersalnego zakazu; przy utrzymujących się trudnościach porozmawiaj z lekarzem.\n\nŹródła:\n" + "\n".join(s["url"] for s in sources), "hashtags": ["#sen", "#trening", "#ćwiczenia", "#badania", "#Shorts"], "pinned_comment": "Czy jedna zła noc po treningu zmieniła kiedyś Twoje podejście?", "title_template": "courtroom_sleep_context", "description_template": "short_context", "distribution_lane": "hybrid", "primary_query": "trening wieczorem", "secondary_queries": ["trening wieczorem sen", "ćwiczenia wieczorem sen", "trening przed snem"], "metadata_hypothesis": "Courtroom roles make a universal sleep accusation easy to understand while systematic reviews keep the verdict conditional.", "api_tags": ["trening wieczorem", "ćwiczenia a sen", "wieczorny trening", "jakość snu", "badania sen"], "source_urls": [s["url"] for s in sources]}

write("research_pack.json", research)
write("script.json", script)
write("compliance.json", {"passed": True, "fixes": ["Removed exercise prescriptions, doses, treatment and insomnia instructions.", "Kept average findings conditional and stated heterogeneity and individual response.", "Avoided claiming late intense training is always safe; limited payoff to no universal ban and clinician discussion for persistent difficulty."] , "cleaned_script": script})
write("fact_review.json", {"passed": True, "checks": [{"claim_id": c["id"], "passed": True, "issue": "", "required_change": ""} for c in claims], "unsupported_script_statements": [], "notes": ["No exercise quantity, intensity prescription or timing instruction is spoken.", "The word always is explicitly challenged rather than asserted.", "Systematic-review limitations and individual response are preserved."]})
write("frame_plan.json", {"grade": "bright premium 2D courtroom editorial cartoon", "light": "warm courtroom light with cobalt judge, coral prosecution and mint defense accents", "lens": "wide accusation, macro challenge, medium exhibit, wide second exhibit, extreme reversal, macro context, medium verdict and wide payoff", "frames": frames})
write("qa.json", qa)
write("publish_package.json", publish)
write("codex_strategy.json", strategy)
write("retention_plan.json", {"version": "9.0-retention", "duration_lane": "core", "target_duration_s": 20.0, "first_proof_beat": 2, "turn_beat": 4, "payoff_beat": 6, "spoken_cta": False, "cadence": {"publications_today": 1, "slot_index": 1, "minimum_gap_hours": 4.0}, "creative_fingerprint": {"hook_family": "courtroom accusation and challenge", "protagonist_mode": "judge, prosecution and defense objects", "story_engine": "courtroom", "proof_device": "two systematic-review exhibits", "environment": "whimsical courtroom", "edit_grammar": "accusation, question, defense, evidence, reversal, context, verdict", "payoff_device": "no universal ban plus clinician boundary", "tts_delivery": "lively conversational male Charon", "compared_runs": strategy["structure_variation"]["compared_runs"], "changed_axes": ["hook_family", "protagonist_mode", "story_engine", "proof_device", "environment", "edit_grammar", "payoff_device"]}})
print(RUN)
